### ISSUE TITLE
Metacoder observation table names, calculation functions, and dplyr style additions to the package?

### ISSUE THREAD

**Issue by grabear** [grunwaldlab/metacoder#254]
# Introduction
I'm not sure if this is relevant for all of your workflows, but I was thinking about the naming conventions used in metacoder and phyloseq.  

For the project I'm working on we decided to go with a different naming convention for the observation data (aka `names(mc_obj$data)`).  Our project imports the data using phylsoeq and then converts it with `parse_phyloseq`, so the context may be limited to this function:

```yaml
# The metacoder_obj$data will contain the following tables.
# The keys here are the old phyloseq table names, and the values are the new table names
...
otu_table: "otu_abundance"
tax_data: "otu_annotations"
sample_data: "sample_data"
phy_tree: "phy_tree"
```
(**Note:** _The "otu_annotations" table makes more sense to with respect to https://github.com/grunwaldlab/metacoder/pull/253_
After calculation, I decided to use these other naming conventions to match what we had above, and they seem to be more intuitive.
```yaml
# These new tables are created by metacoder's calculation functions
...
calc_taxon_abund(otu_abundance): "taxa_abundance"
calc_obs_props(otu_abundance): "otu_proportions"
calc_obs_props(otu_proportions): "taxa_proportions"
...
```

# Questions

### 1.  Do you like these ideas?  

* I think it would make more sense to the end user.  Especially those who are newer to microbiome work.
    * We could make them shorter too:
    ```yaml
    otu_table: 
        option1: "otu_abund"
        option2: "otu_counts"
    tax_data: 
        option1: "otu_anno"
        option2: "otu_taxa"
    sample_data: 
        option1: "sample_data"
        option2: "metadata"
     phy_tree: "phy_tree"
    ```

### 2.  Would you consider manipulating the way the `calc_*` functions work?

* I don't want to change the underlying functionality, I just  want to add an additional way to direct the output:

    ```r
        # Allowing the user to do this:
        > mc_obj$data$new_table <- calc_*(mc_obj, ...)
        # And this:
        > calc_*(mc_obj, new="new_table")
        # The table is added to mc_obj$data implicitely unless directed
        ```

### 3.  Would you consider adding functionality to the `calc_*` functions so that they generate default observation table names based on verified data types (e.g. phyloseq)?

* Below are my ideas with shortned naming conventions:

```yaml
...
# if data = "otu_abund", then table_name = "taxa_abund"
calc_taxon_abund(otu_abund): "taxa_abund"
# if data = "otu_abund", then table_name = "otu_prop"
calc_obs_props(otu_abund): "otu_prop"
# if data = "otu_prop", then table_name = "taxa_prop"
calc_obs_props(otu_prop): "taxa_prop"
...
```

* This would probably be hard locked to specific circumstances like `parse_phyloseq` in the short term.

# Final

I can work on most of these items on my fork.
